--
-- -- DAP keymaps
-- map("n", "<leader>db", "<cmd>DapToggleBreakpoint<CR>", { desc = "DAP: Toggle Breakpoint" })
-- map("n", "<leader>dr", "<cmd>DapToggleRepl<CR>", { desc = "DAP: Toggle REPL" })
-- map("n", "<leader>dc", "<cmd>DapContinue<CR>", { desc = "DAP: Continue" })
-- map("n", "<leader>di", "<cmd>DapStepInto<CR>", { desc = "DAP: Step Into" })
-- map("n", "<leader>do", "<cmd>DapStepOut<CR>", { desc = "DAP: Step Out" })
-- map("n", "<leader>dO", "<cmd>DapStepOver<CR>", { desc = "DAP: Step Over" })
-- map("n", "<leader>dP", "<cmd>DapPause<CR>", { desc = "DAP: Pause" })
-- map("n", "<leader>dt", "<cmd>DapTerminate<CR>", { desc = "DAP: Terminate" })
--
-- -- custom function keymaps
-- local dap = require("dap")
-- local dap_widgets = require("dap.ui.widgets")
-- local function dap_cond_bp()
-- 	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
-- end
--
-- local function dap_continue_args()
-- 	require("dap")
-- 	dap.continue({ before = get_args })
-- end
-- map("n", "<leader>dB", dap_cond_bp, { desc = "DAP: Conditional Breakpoint" })
-- map("n", "<leader>da", dap_continue_args, { desc = "DAP: Continue with Args" })
-- map("n", "<leader>dC", dap.run_to_cursor, { desc = "DAP: Run to Cursor" })
-- map("n", "<leader>dg", dap.goto_, { desc = "DAP: Go to Line" })
-- map("n", "<leader>dj", dap.down, { desc = "DAP: Move Down Frame" })
-- map("n", "<leader>dk", dap.up, { desc = "DAP: Move Up Frame" })
-- map("n", "<leader>dl", dap.run_last, { desc = "DAP: Run Last" })
-- map("n", "<leader>ds", dap.session, { desc = "DAP: Show Session Info" })
-- map("n", "<leader>dw", dap_widgets.hover, { desc = "DAP: Hover Widget" })
-- -- Neogen keymaps
-- map("n", "<leader>nf", "<cmd>Neogen func<CR>", { desc = "Neogen: Generate Function docs" })
-- map("n", "<leader>nt", "<cmd>Neogen type<CR>", { desc = "Neogen: Generate Type/Class docs" })
